services:
  all-in-on-eeg-dataset-downloader:
    image: registry.gitlab.tugraz.at/hereditary/all-in-on-eeg:dataset-downloader_master
    build:
      context: .
      dockerfile: backend/Dockerfile.dataset-downloader
    restart: "no"
    environment:
      # Real dataset: https://cloud.tugraz.at/index.php/s/kDEwkJbSggxZW2c
      # Smaller set for testing: https://cloud.tugraz.at/index.php/s/bsyXsEdd2W39eic
      DATASET_URL: https://cloud.tugraz.at/index.php/s/kDEwkJbSggxZW2c
      DATASET_STORAGE_DIR: /app/data/datasets
    volumes:
      - datasets:/app/data/datasets
    networks:
      - web

  all-in-on-eeg-backend:
    image: registry.gitlab.tugraz.at/hereditary/all-in-on-eeg:backend_master
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATASET_STORAGE_DIR: /app/data/datasets
      MODEL_OUTPUT_STORAGE_DIR: /app/data/model_outputs
      MNE_LOG_LEVEL: ERROR
      SERVER: "true"
    # ports:
    #   - "8000:8000"
    volumes:
      - datasets:/app/data/datasets:ro
      - model-outputs:/app/data/model_outputs
    depends_on:
      all-in-on-eeg-dataset-downloader:
        condition: service_completed_successfully
    networks:
      - web

  all-in-on-eeg-frontend:
    image: registry.gitlab.tugraz.at/hereditary/all-in-on-eeg:frontend_master
    build:
      context: .
      dockerfile: frontend/Dockerfile
    # ports:
    #   - "3000:80"
    depends_on:
      - all-in-on-eeg-backend
    networks:
      - web
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.allinoneeg_backend-http.rule=Host(`hereditary.cgv.tugraz.at`) && PathPrefix(`/all-in-on-eeg/`)
      - traefik.http.routers.allinoneeg_backend-http.entrypoints=http
      - traefik.http.routers.allinoneeg_backend-https.rule=Host(`hereditary.cgv.tugraz.at`) && PathPrefix(`/all-in-on-eeg/`)
      - traefik.http.routers.allinoneeg_backend-https.entrypoints=https

      - traefik.http.routers.allinoneeg_backend-https.tls=true
      - traefik.http.routers.allinoneeg_backend-https.tls.certresolver=letsencrypt

      - "traefik.http.routers.allinoneeg_backend-http.middlewares=redirect,allinoneeg_backend_sp@docker"
      - "traefik.http.routers.allinoneeg_backend-https.middlewares=redirect,allinoneeg_backend_sp@docker"
      - "traefik.http.middlewares.allinoneeg_backend_sp.stripprefix.prefixes=/all-in-on-eeg"
      - "traefik.http.middlewares.allinoneeg_backend_sp.stripprefix.forceSlash=false"
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.services.allinoneeg_backend.loadbalancer.server.port=80

networks:
  internal:
    external: false
  web:
    external: true

volumes:
  datasets:
  model-outputs:
