[project]
name = "allinoneeg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "fastapi[standard]>=0.141.1",
  "mne>=1.13.2",
  "mne-connectivity>=0.9.0",
  "pydantic-settings>=2.15.0",
  "python-dotenv>=1.2.3",
  "scikit-learn>=1.9.1",
  "selfeeg>=0.2.2",
  "shap>=0.52.0",
  "torch>=2.14.0",
  "torchaudio>=2.11.0",
  "umap-learn>=0.5.12",
  "xgboost>=3.4.1",
]

[tool.ruff]
line-length = 120
exclude = ["backend/experiments_xeegnet", ".venv"]

[tool.uv]
index = [{ name = "pytorch-cpu", url = "https://download.pytorch.org/whl/cpu", explicit = true }]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
torchaudio = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]

[dependency-groups]
dev = [
  "ipykernel>=7.3.0",
  "isort>=9.0.1",
  "mass-ts>=0.1.4",
  "pymupdf>=1.28.2",
  "pypdf>=6.19.0",
  "ruff>=0.16.7",
  "selenium>=4.49.0",
  "selfeeg[interactive]>=0.2.2",
]
