import logging
import os
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


class CONFIG:
    # APP
    TITLE = "EEGlass Backend"

    # CORS
    ORIGINS = [
        "http://localhost",
        "http://localhost:3000",
    ]

    # DATA
    DATASET_STORAGE_DIR = os.getenv("DATASET_STORAGE_DIR", "data/datasets")
    MODEL_OUTPUT_STORAGE_DIR = os.getenv("MODEL_OUTPUT_STORAGE_DIR", "data/model_outputs")
    MODEL_PREDICTION_WORKERS = int(os.getenv("MODEL_PREDICTION_WORKERS", "1"))
    MODEL_OUTPUT_TMP_MAX_AGE_SECONDS = int(os.getenv("MODEL_OUTPUT_TMP_MAX_AGE_SECONDS", "3600"))

    # MODEL FEATURE IMPORTANCE
    MODEL_FEATURE_IMPORTANCE_DEFAULT_METHOD = os.getenv("MODEL_FEATURE_IMPORTANCE_DEFAULT_METHOD", "shap")
    MODEL_FEATURE_IMPORTANCE_BACKEND_MODEL = os.getenv("MODEL_FEATURE_IMPORTANCE_BACKEND_MODEL", "xgboost")
    MODEL_FEATURE_IMPORTANCE_MIN_ROWS = int(os.getenv("MODEL_FEATURE_IMPORTANCE_MIN_ROWS", "3"))
    MODEL_FEATURE_IMPORTANCE_MIN_CLASSES = int(os.getenv("MODEL_FEATURE_IMPORTANCE_MIN_CLASSES", "2"))
    MODEL_FEATURE_IMPORTANCE_XGBOOST_N_ESTIMATORS = int(
        os.getenv("MODEL_FEATURE_IMPORTANCE_XGBOOST_N_ESTIMATORS", "80")
    )
    MODEL_FEATURE_IMPORTANCE_XGBOOST_MAX_DEPTH = int(os.getenv("MODEL_FEATURE_IMPORTANCE_XGBOOST_MAX_DEPTH", "3"))
    MODEL_FEATURE_IMPORTANCE_XGBOOST_LEARNING_RATE = float(
        os.getenv("MODEL_FEATURE_IMPORTANCE_XGBOOST_LEARNING_RATE", "0.08")
    )
    MODEL_FEATURE_IMPORTANCE_XGBOOST_RANDOM_STATE = int(
        os.getenv("MODEL_FEATURE_IMPORTANCE_XGBOOST_RANDOM_STATE", "42")
    )

    # MODEL AGGREGATION
    MODEL_PATIENT_AGGREGATION_STRATEGY = os.getenv("MODEL_PATIENT_AGGREGATION_STRATEGY", "disease_threshold")
    MODEL_PATIENT_ALZHEIMER_WINDOW_THRESHOLD = float(
        os.getenv(
            "MODEL_PATIENT_ALZHEIMER_WINDOW_THRESHOLD",
            os.getenv("MODEL_PATIENT_DISEASE_WINDOW_THRESHOLD", "0.3"),
        )
    )
    MODEL_PATIENT_FTD_WINDOW_THRESHOLD = float(
        os.getenv(
            "MODEL_PATIENT_FTD_WINDOW_THRESHOLD",
            os.getenv("MODEL_PATIENT_DISEASE_WINDOW_THRESHOLD", "0.3"),
        )
    )

    # LOGGING
    LOG_LEVEL = "DEBUG"

    # API
    GZIP_MINIMUM_SIZE = int(os.getenv("GZIP_MINIMUM_SIZE", "1000"))